package ETL_Assignment;

import java.io.IOException;

import com.squareup.okhttp.*;

public class test2 {
	public static void main(String[] args) throws IOException {
		// TODO Auto-generated method stub
		String str="<html>\r\n"
				+ "<body>\r\n"
				+ "<table style=\"width: 100%;\">\r\n"
				+ "<tbody>\r\n"
				+ "<tr>\r\n"
				+ "<td style=\"width: 20.0000%;\">Attribute Name\r\n"
				+ "<br>\r\n"
				+ "</td>\r\n"
				+ "<td style=\"width: 20.0000%;\">Attribute Type\r\n"
				+ "<br>\r\n"
				+ "</td>\r\n"
				+ "<td style=\"width: 20.0000%;\">Friendly Name\r\n"
				+ "<br>\r\n"
				+ "</td>\r\n"
				+ "<td style=\"width: 20.0511%;\">Identifiability\r\n"
				+ "<br>\r\n"
				+ "</td>\r\n"
				+ "<td style=\"width: 20.0511%;\">Category</td>\r\n"
				+ "</tr>\r\n"
				+ "<tr>\r\n"
				+ "<td style=\"width: 20.0000%;\">Activity\r\n"
				+ "<br>\r\n"
				+ "</td>\r\n"
				+ "<td style=\"width: 20.0000%;\">Manual\r\n"
				+ "<br>\r\n"
				+ "</td>\r\n"
				+ "<td style=\"width: 20.0000%;\">Activity\r\n"
				+ "<br>\r\n"
				+ "</td>\r\n"
				+ "<td style=\"width: 20.0000%;\">1.0\r\n"
				+ "<br>\r\n"
				+ "</td>\r\n"
				+ "<td style=\"width: 20.0000%;\">\r\n"
				+ "<br>\r\n"
				+ "</td>\r\n"
				+ "</tr>\r\n"
				+ "<tr>\r\n"
				+ "<td style=\"width: 20.0000%;\">full_name\r\n"
				+ "<br>\r\n"
				+ "</td>\r\n"
				+ "<td style=\"width: 20.0000%;\">IDSoR Attribute\r\n"
				+ "<br>\r\n"
				+ "</td>\r\n"
				+ "<td style=\"width: 20.0000%;\">full_name\r\n"
				+ "<br>\r\n"
				+ "</td>\r\n"
				+ "<td style=\"width: 20.0000%;\">1.0\r\n"
				+ "<br>\r\n"
				+ "</td>\r\n"
				+ "<td style=\"width: 20.0000%;\">Personal sensitive\r\n"
				+ "<br>\r\n"
				+ "</td>\r\n"
				+ "</tr>\r\n"
				+ "<tr>\r\n"
				+ "<td style=\"width: 20.0000%;\">zipcode\r\n"
				+ "<br>\r\n"
				+ "</td>\r\n"
				+ "<td style=\"width: 20.0000%;\">IDSoR Attribute\r\n"
				+ "<br>\r\n"
				+ "</td>\r\n"
				+ "<td style=\"width: 20.0000%;\">Postal Code\r\n"
				+ "<br>\r\n"
				+ "</td>\r\n"
				+ "<td style=\"width: 20.0000%;\">1.0\r\n"
				+ "<br>\r\n"
				+ "</td>\r\n"
				+ "<td style=\"width: 20.0000%;\">PII, mailing\r\n"
				+ "<br>\r\n"
				+ "</td>\r\n"
				+ "</tr>\r\n"
				+ "<tr>\r\n"
				+ "<td style=\"width: 20.0000%;\">ssn\r\n"
				+ "<br>\r\n"
				+ "</td>\r\n"
				+ "<td style=\"width: 20.0000%;\">IDSoR Attribute\r\n"
				+ "<br>\r\n"
				+ "</td>\r\n"
				+ "<td style=\"width: 20.0000%;\">Citizen ID\r\n"
				+ "<br>\r\n"
				+ "</td>\r\n"
				+ "<td style=\"width: 20.0000%;\">1.0\r\n"
				+ "<br>\r\n"
				+ "</td>\r\n"
				+ "<td style=\"width: 20.0000%;\">PII, Derived Attributes\r\n"
				+ "<br>\r\n"
				+ "</td>\r\n"
				+ "</tr>\r\n"
				+ "<tr>\r\n"
				+ "<td style=\"width: 20.0000%;\">Activity ID\r\n"
				+ "<br>\r\n"
				+ "</td>\r\n"
				+ "<td style=\"width: 20.0000%;\">Manual\r\n"
				+ "<br>\r\n"
				+ "</td>\r\n"
				+ "<td style=\"width: 20.0000%;\">Activity ID\r\n"
				+ "<br>\r\n"
				+ "</td>\r\n"
				+ "<td style=\"width: 20.0000%;\">1.0\r\n"
				+ "<br>\r\n"
				+ "</td>\r\n"
				+ "<td style=\"width: 20.0000%;\">sensitive, not sensitive, Ground Mailing, Personal Sensitive, new category, HR Data, PR Data, Postal Code, new tag for demo, GDPR\r\n"
				+ "<br>\r\n"
				+ "</td>\r\n"
				+ "</tr>\r\n"
				+ "<tr>\r\n"
				+ "<td style=\"width: 20.0000%;\">date_of_birth\r\n"
				+ "<br>\r\n"
				+ "</td>\r\n"
				+ "<td style=\"width: 20.0000%;\">IDSoR Attribute\r\n"
				+ "<br>\r\n"
				+ "</td>\r\n"
				+ "<td style=\"width: 20.0000%;\">date_of_birth\r\n"
				+ "<br>\r\n"
				+ "</td>\r\n"
				+ "<td style=\"width: 20.0000%;\">0.8\r\n"
				+ "<br>\r\n"
				+ "</td>\r\n"
				+ "<td style=\"width: 20.0000%;\">Personal sensitive\r\n"
				+ "<br>\r\n"
				+ "</td>\r\n"
				+ "</tr>\r\n"
				+ "</tbody>\r\n"
				+ "</table>\r\n"
				+ "</body>\r\n"
				+ "</html>";
		OkHttpClient client = new OkHttpClient();
				MediaType mediaType = MediaType.parse("application/json");
				RequestBody body = RequestBody.create(mediaType, "{\"assetId\":"+"\"37aded23-d0bd-48b3-8a19-b79e45cda138\""+",\"typeId\":\"00000000-0000-0000-0000-000000003114\",\"value\":"+"\""+str+"\""+"}");
				Request request = new Request.Builder()
				  .url("https://ia-53.collibra.com/rest/2.0/attributes")
				  .method("POST", body)
				  .addHeader("accept", "application/json")
				  .addHeader("Content-Type", "application/json")
				  .addHeader("Authorization", "Basic YWRlc2htdWtoOlRlc3RtZUAxMjM=")
//				  .addHeader("Cookie", "AWSALBTG=VnSlM/M3cUOimfBqkMmLfx8VZ7P335a8zmhfYZTR37S3SvuohhzQ9KCs6DWE25rZty6uy2uNdoZ6bYiJTjBjuja9XrGZx9SEvLcE4hdotGdYqaIrkAIXa5PDCYUYSq36N6Y5zI/z6Pe8vmDNJtk1ZYKMmtXKX0rQcaaW2Xuxr3tfcWQJyBQ=; AWSALBTGCORS=VnSlM/M3cUOimfBqkMmLfx8VZ7P335a8zmhfYZTR37S3SvuohhzQ9KCs6DWE25rZty6uy2uNdoZ6bYiJTjBjuja9XrGZx9SEvLcE4hdotGdYqaIrkAIXa5PDCYUYSq36N6Y5zI/z6Pe8vmDNJtk1ZYKMmtXKX0rQcaaW2Xuxr3tfcWQJyBQ=; JSESSIONID=29559837-6923-4acc-b564-e967f9cbc361")
				  .build();
				Response response = client.newCall(request).execute();
	}

}
